Flexible parser with recursive descent parsing
d-u-d-e/c-compiler pull request #20
Opened 2024-11-14 18:40 UTC by d-u-d-e

resolves #18
resolves #7 
resolves #15 
resolves #8

2024-11-16 09:46 UTC, CremaLuca commented
I don't think having a folder for each type of test is useful, in most cases there will only be one file (test_xxx.py), so I believe it's better to keep them all under `test/. For those special cases that require multiple classes, one can have multiple `unittest.TestCase` class inside one file.

2024-11-17 02:31 UTC, albertoursino requested changes

2024-11-17 08:48 UTC, d-u-d-e commented on compiler/parser/parsers.py
> +    """Pops the first element out of the tokens list and compares it to the expected type.
KISS and DRY.
It's true that we need to look-ahead in the following chapters, but let's make use of the `expect` function as suggested in the book. We will add another method like `peek_tokens` or something to look at the next tokens without popping them. I don't like to pop and check for exceptions in each method. It's repetitive and error-prone.

2024-11-17 08:49 UTC, d-u-d-e commented on compiler/lexer/lexer.py
> +    def __init__(self, token_type: TokenType) -> None:
Sure

2024-11-17 15:10 UTC, CremaLuca approved these changes

2024-11-17 15:19 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        setattr(body, "field_name", "body")
See comments. This is used to render the tree with field names.

2024-11-17 16:25 UTC, CremaLuca approved these changes

2024-11-17 17:39 UTC, albertoursino requested changes

2024-11-17 17:39 UTC, albertoursino commented on compiler/compiler_driver.py
> +                # print parse tree
Not necessary comment.

2024-11-17 17:39 UTC, albertoursino commented on compiler/lexer/lexer.py
> +    def __init__(self, token_type: TokenType, value=None) -> None:
Specify the type of value, e.g. `value: Any = None`

2024-11-17 17:39 UTC, albertoursino commented on compiler/lexer/lexer.py
> +        c_source_file: path to the C source file
I know I'm pity but let's be coherent with capital letters. After the name of the argument and the semicolon, the first letter is always a capital letter.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
@d-u-d-e I put here the field_name. Should we comment its purpose?

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
Also here.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/ast.py
> +        statement.field_name = "body"
This is the way we're calling the `field_name` attributes.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/ast.py
> +    """Gets a pretty string representation for a parse tree.
Change `Gets` in `Generates`

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/ast.py
> +        tree: the parse tree.
Capital letter.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # "int" <identifier> "(" "void" ")" "{" <statement> "}"
I would write a clearer comment:

```Python
# Chapter 1 operation rule: "int" <identifier> "(" "void" ")" "{" <statement> "}"
```

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # no extra junk after function
Comments should start with the capital letter.

https://peps.python.org/pep-0008/#comments

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # chapter 1: the statement is a return statement
Also here.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # chapter 1: "return" <exp> ";"
Here.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # -> Identifier(name="main", parent=None)
Here.

2024-11-17 17:39 UTC, albertoursino commented on compiler/parser/parsers.py
> +    # chapter 1: the expression is a constant
Here.

2024-11-17 17:39 UTC, albertoursino commented on lib/tree/node.py
> +        # use the property setter for further checks
Here.

2024-11-17 17:39 UTC, albertoursino commented on lib/tree/node.py
> +        self.__attach(parent)
Comments should start with a capital letter.

2024-11-17 17:39 UTC, albertoursino commented on lib/tree/node.py
> +        # generator
> Block comments generally consist of one or more paragraphs built out of complete sentences, with each sentence ending in a period.
> You should use one or two spaces after a sentence-ending period in multi-sentence comments, except after the final sentence.
> 
> Ensure that your comments are clear and easily understandable to other speakers of the language you are writing in.

https://peps.python.org/pep-0008/#comments

2024-11-17 17:39 UTC, albertoursino commented on tests/test_tree.py
Comments should start with a capital letter .

2024-11-17 17:39 UTC, albertoursino commented on tests/test_tree.py
> +        self.assertEqual(len(self.t), 7)
What about:
    
```Python
def test_tree_length(self):
     self.assertEqual(len(self.t), 7)
```

2024-11-17 17:39 UTC, albertoursino commented on tests/test_parsers.py
@d-u-d-e @Fabio-Marangoni @CremaLuca can you please review these new tests? 😊

2024-11-17 17:43 UTC, albertoursino commented on lib/tree/node.py
> +        # update pointers
Comments should start with a capital letter.

2024-11-17 17:43 UTC, albertoursino commented on lib/tree/node.py
> +        # make sure we don't set the parent to a descendant of self
Comments should start with a capital letter.

2024-11-17 17:45 UTC, albertoursino commented on compiler/parser/ast.py
> +    def get_node_repr(self, level: int, fill: str, pre: str = "", end: str = "") -> str:
What about moving this function at the bottom of the file above `get_node_repr`?

2024-11-17 17:51 UTC, d-u-d-e commented on compiler/lexer/lexer.py
> +        c_source_file: path to the C source file
You didn't catch it when it was merged :)

2024-11-17 17:55 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
That will break the pretty printer. The pretty printer checks for a "field_name" attribute.

2024-11-17 17:55 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
That will break the pretty printer. The pretty printer checks for a "field_name" attribute.

2024-11-17 18:00 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
I tested it and it works.

> The pretty printer checks for a "field_name" attribute.

The `Identifier` and `Statement` ASTNodes have this attribute, indeed.

2024-11-17 18:00 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        statement.field_name = "body"
Can I mark this as resolved?

2024-11-17 18:01 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        tree: the parse tree.
You mean colon right?

2024-11-17 18:02 UTC, d-u-d-e commented on compiler/parser/parsers.py
> +    # "int" <identifier> "(" "void" ")" "{" <statement> "}"
That was a very crude comment. You are right.

2024-11-17 18:11 UTC, d-u-d-e commented on compiler/parser/ast.py
> +    def get_node_repr(self, level: int, fill: str, pre: str = "", end: str = "") -> str:
Do you mean to move `generate_pretty_ast_repr`? If so, where exactly?

2024-11-17 18:30 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
But we don't want to add it to every statement. Only the FunctionDefinition node should know about the body field name, at least currently. A static global variable initialization is a statement that lives outside any function. It should not have a body field name, although this code creates it.

2024-11-18 18:00 UTC, albertoursino commented on compiler/parser/ast.py
> +    def get_node_repr(self, level: int, fill: str, pre: str = "", end: str = "") -> str:
Sorry, I meant to move this function at the bottom of the file, above `generate_pretty_ast_repr`.

2024-11-18 18:05 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
So, this is the problem Ruff raises:

![image](https://github.com/user-attachments/assets/89164c55-fe33-46ed-ae9a-4048be33a3a9)

and it suggests to use:

```Python
identifier.field_name = "name"
statement.field_name = "body"
```

and for doing this, we have to initialize these attributes on the `__init__` methods of the Identifier and Statement AST nodes.

But you say:

> But we don't want to add it to every statement.

So we have two possibilities:

1. We ignore Ruff in this case;
2. We find another way to assign these two attributes (is there a way not to use attributes)?

2024-11-18 18:06 UTC, albertoursino commented on compiler/parser/ast.py
> +        statement.field_name = "body"
Yes but let's finish the discussion at https://github.com/d-u-d-e/c-compiler/pull/20/files#r1845544519.

2024-11-18 19:03 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
We can just do ` identifier.field_name = "name"` and `statement.field_name = "body"`. Ruff is happy then.

2024-11-18 19:08 UTC, d-u-d-e commented on compiler/parser/ast.py
> +    def get_node_repr(self, level: int, fill: str, pre: str = "", end: str = "") -> str:
We would need to move the full class `ASTNode` below. I prefer to keep it above since all the following classes inherit from this one. Instead I can move `generate_pretty_ast_repr` up just below the `ASTNode` class if you like it close.

2024-11-18 19:18 UTC, d-u-d-e commented on tests/test_parsers.py
> +        child = output.children.pop()
This is false. You are being lucky here because the first popped node is a Statement.

2024-11-18 19:18 UTC, d-u-d-e commented on tests/test_parsers.py
> +    def test_parse_function_invalid_token_list(self):
It's okay to have these tests, but...
do these tests add more value to the author's suite test?

2024-11-18 19:19 UTC, d-u-d-e commented on tests/test_parsers.py
> +    def test_parse_function_invalid_token_list(self):
@CremaLuca @Fabio-Marangoni just a reminder for you to review this PR.
I know it's a lot of files but we can't proceed with the next stage unless this is merged.

2024-11-18 19:35 UTC, albertoursino commented on tests/test_parsers.py
> +    def test_parse_function_invalid_token_list(self):
> It's okay to have these tests, but...
> do these tests add more value to the author's suite test?

That's a nice observation tho, we should check

2024-11-19 10:19 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
We can use python slots to limit the dynamic creation of attributes. See https://wiki.python.org/moin/UsingSlots.

2024-11-19 10:21 UTC, d-u-d-e commented on tests/test_parsers.py
> +        child = output.children.pop()
The identifier (name of function) is also a child of the function node. I decided to do this so that the pretty printer can find it while looking at the children of the function node.

2024-11-19 10:38 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
> We can just do ` identifier.field_name = "name"` and `statement.field_name = "body"`. Ruff is happy then. I don't think we have _to initialize these attributes on the_ `__init__` _methods of the Identifier and Statement AST nodes_. They get set at runtime.

Ruff is not happy:

```Shell
compiler/parser/ast.py:112: error: "Identifier" has no attribute "field_name"  [attr-defined]
compiler/parser/ast.py:113: error: "Statement" has no attribute "field_name"  [attr-defined]
```

2024-11-19 10:59 UTC, albertoursino commented on tests/test_parsers.py
> +    def test_parse_function_invalid_token_list(self):
Well, tests that raise an exception probably are not necessary because we are already testing invalid C source files with the test suit. The other tests can be useful to check if the functions return the proper object with the expected attributes.

2024-11-19 11:13 UTC, Fabio-Marangoni approved these changes

2024-11-19 11:25 UTC, albertoursino commented on tests/test_parsers.py
> +        child = output.children.pop()
Should we create a for loop to check that the child is present?

2024-11-19 11:41 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
We need to change the pretty printer. Instead of looking for an attribute, it should check if the attribute is not None.

2024-11-19 11:42 UTC, d-u-d-e commented on tests/test_parsers.py
> +        child = output.children.pop()
We could.

2024-11-19 11:44 UTC, d-u-d-e commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
Also we cannot have it as a class attribute otherwise changing it will affect all objects.

2024-11-19 12:29 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
> We need to change the pretty printer. Instead of looking for an attribute, it should check if the attribute is not None.

It's easy: we just need to change one line of code.

2024-11-19 12:31 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
> Also we cannot have it as a class attribute otherwise changing it will affect all objects.

I mean: what's the problem of having this attribute in all `ASTNode` nodes?

2024-11-19 15:12 UTC, albertoursino commented on compiler/parser/ast.py
> +        self.field_name: str | None = None
Seems good to me.

2024-11-19 15:27 UTC, albertoursino commented
We will write tests for the pretty printer with https://github.com/d-u-d-e/c-compiler/issues/26, and we will create another PR because we are introducing too many changes already with this one.

2024-11-19 15:28 UTC, albertoursino approved these changes
Super good 💯

2024-11-19 15:33 UTC, Fabio-Marangoni approved these changes

2024-11-19 15:40 UTC, albertoursino approved these changes

2024-11-20 09:31 UTC, Fabio-Marangoni approved these changes

2024-11-23 16:59 UTC, merged