Introducing assembly generation
d-u-d-e/c-compiler pull request #27
Opened 2024-11-24 14:18 UTC by d-u-d-e

This PR introduces the assembly generation stage with the assembly ast.
This is a very rough translation soon to be replaced by the TACKY representation.
Do you suggest to use the `traverse` method available in the tree library to convert the parse tree into the assembly AST?

2024-11-26 16:35 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +            f"Node {stmt} cannot be converted into a list of Assembly instructions"
Some comment as before about the quotation marks.

2024-11-26 16:36 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError("Parse tree root node is not a Program node")
I would write:

```Python
raise RuntimeError(f"The root node of the parse tree '{parse_tree}' is not a Program node")
```

to be clearer.

2024-11-26 16:39 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +def convert_statement(stmt: parser_ast.Statement) -> list[assembly_ast.Instruction]:
I would write `statement` instead of `stmt` to be more clear.

2024-11-26 16:45 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
It's interesting that you used `RuntimeError` instead of `ValueError`.

One uses `ValueError` when the input passed to a function is bad ([source](https://docs.python.org/3/library/exceptions.html#ValueError)), but in this case you shouldn't use it because if one passes a `parser_ast.Exp` object without being a `parser_ast.Constant` object, well, it's still respecting the parameter type specified by the type hint `exp: parser_ast.Exp`.

That said, the presence of a doc string explaining the function behavior is essential here.

2024-11-26 19:00 UTC, d-u-d-e commented
> Well done 🚀
> 
> Are the tests from the test suit succeeding?

Yes. They basically instruct our driver to perform the codegen stage and check for valid or invalid source files as we did with the parse stage.

2024-11-26 19:10 UTC, d-u-d-e commented on compiler/assembly_generation/generator.py
> +def convert_return_statement(stmt: parser_ast.Return) -> list[assembly_ast.Instruction]:
`stmt` is rather idiomatic, especially in sql code

2024-11-26 19:17 UTC, d-u-d-e commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
Waht about `NotImplementedError`?

2024-11-26 22:12 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +def convert_return_statement(stmt: parser_ast.Return) -> list[assembly_ast.Instruction]:
well, it's a not big of deal, if you think `stmt` is good leave it.

2024-11-26 22:13 UTC, albertoursino commented
> ey basically instruct our driver to perform the codegen stage a

Do we need to write our own tests?

2024-11-26 22:17 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
I don't think we should use it.

[NotImplementedError built-in exception](https://docs.python.org/3/library/exceptions.html#NotImplementedError):
> This exception is derived from [RuntimeError](https://docs.python.org/3/library/exceptions.html#RuntimeError). In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method, or while the class is being developed to indicate that the real implementation still needs to be added.

It's used only in abstract class' methods

2024-11-26 22:47 UTC, d-u-d-e commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
I can leave RuntimeError but they say "or while the class is being developed to indicate that the real implementation still needs to be added.

2024-11-26 22:51 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
They're still talking about the abstract class.

2024-11-26 23:02 UTC, d-u-d-e commented on compiler/assembly_generation/generator.py
> +        raise RuntimeError(f"Node {exp} cannot be converted to Assembly Operand node")
Yes although there's a bit of discussione here https://softwareengineering.stackexchange.com/questions/231397/is-it-conventional-to-raise-a-notimplementederror-for-methods-whose-implementati and https://stackoverflow.com/questions/44315961/when-to-use-raise-notimplementederror.

2024-12-01 20:58 UTC, albertoursino commented
> Do you suggest to use the `traverse` method available in the tree library to convert the parse tree into the assembly AST?

Can you please explain me better this question? How and where do you want to use the `traverse` method?

2024-12-01 21:13 UTC, albertoursino requested changes

2024-12-01 21:13 UTC, albertoursino commented on lib/ast/ast.py
> +    return root.get_node_repr(0, fill)
I would refactor this function in something like:

```Python
def generate_pretty_ast_repr(tree: Tree) -> str:
    """Generates a pretty string representation for a parse tree.

    Args:
        tree: The parse tree whose root is an `ASTNode`.

    Raises:
        TypeError: If the root of the tree is not an `ASTNode`.

    Returns:
        A formatted string representation of the tree.
    """
    if not isinstance(tree.root, ASTNode):
        raise TypeError("Tree root must be an ASTNode.")
    
    fill = "   "
    root: ASTNode = tree.root
    return root.get_node_repr(0, fill)
```

And maybe I would put it inside the `ASTNode` class, what do you think?

2024-12-01 21:13 UTC, albertoursino commented on compiler/compiler_driver.py
> +        parse_tree = Tree(root=None)
`parse_tree` is going to be overwritten by `parse_tree = parsers.run_parser(tokens)` so I would write

```Python
parse_tree: Tree = None
```

2024-12-01 21:13 UTC, albertoursino commented on compiler/assembly_generation/generator.py
Like in the file “parsers.py”, I would put `generate_assembly_ast` as the first function, and then all the others in order from the most abstract (like `convert_program`) to the least abstract. 

In this way we are more coherent, and external viewers can understand the code more easily.

2024-12-02 07:37 UTC, d-u-d-e commented
> > Do you suggest to use the `traverse` method available in the tree library to convert the parse tree into the assembly AST?
> 
> Can you please explain me better this question? How and where do you want to use the `traverse` method?

2024-12-02 07:41 UTC, d-u-d-e commented on lib/ast/ast.py
> +    return root.get_node_repr(0, fill)
I wouldn't put it inside the `ASTNode` class, because it takes a tree as parameter.

2024-12-02 07:48 UTC, d-u-d-e commented on compiler/compiler_driver.py
> +        parse_tree = Tree(root=None)
Yes, but MyPy is not happy. `generate_assembly_ast` needs a `Tree` type.

2024-12-02 11:53 UTC, albertoursino commented on lib/ast/ast.py
> +    return root.get_node_repr(0, fill)
Ok, looks good then

2024-12-02 12:06 UTC, albertoursino commented on compiler/compiler_driver.py
> +        parse_tree = Tree(root=None)
Strange, it should work because I specified it's a tree with the type hint.

2024-12-02 12:17 UTC, albertoursino commented on compiler/compiler_driver.py
> +        parse_tree = Tree(root=None)
Ok, what about this?

```python
parse_tree = None
for current_stage in stages:
    if current_stage == "lex":
        tokens = lexer.run_lexer(preprocessed_file.name)
    elif current_stage == "parse":
        parse_tree = parsers.run_parser(tokens)
        logger.debug("Parse tree:\n" + generate_pretty_ast_repr(parse_tree))
    elif current_stage == "codegen":
        if parse_tree is None:
            raise ValueError(
                "Parse tree is required for the stage 'codegen' but was not generated."
            )
        assembly_ast = generate_assembly_ast(parse_tree)
        logger.debug("Assembly AST:\n" + generate_pretty_ast_repr(assembly_ast))

    # Stop once we've reached the chosen stage
    if current_stage == stage:
        break
```

We avoid useless initializations, Mypy is fine, and the code is better maintainable.

2024-12-02 12:18 UTC, Fabio-Marangoni submitted a review, later dismissed

2024-12-02 12:49 UTC, albertoursino requested changes

2024-12-02 12:49 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +    return ast_prog
I would write:

```python
return assembly_ast.Program(ast_func_def)
```

for clearance.

2024-12-02 12:49 UTC, albertoursino commented on compiler/assembly_generation/generator.py
> +    return Tree(prog)
I would rename `prog` in `ast_prog` as you did with `ast_func_def` to maintain consistency.

2024-12-02 17:17 UTC, d-u-d-e commented on compiler/compiler_driver.py
> +        parse_tree = Tree(root=None)
What about `assert parse_tree is not None`? It's less cluttered. Assertions should be used when a recovery action is not needed. It's an unrecoverable error.

2024-12-02 23:18 UTC, albertoursino approved these changes

2024-12-02 23:26 UTC, Fabio-Marangoni approved these changes

2024-12-03 07:21 UTC, merged