Assembly code emission (Chapter 1) PR
d-u-d-e/c-compiler pull request #28
Opened 2024-12-03 18:01 UTC by Fabio-Marangoni

This branch introduces the code emission stage of the compiler. The translation between Assembly AST and Assembly code has been structured following the same scheme of the previous [conversion from Parse AST to Assembly AST](https://github.com/d-u-d-e/c-compiler/blob/develop/compiler/assembly_generation/generator.py).
The output assembly code _filename.s_ gets stored inside the folder _compiler/code_emission/output/_ ; you will probably want to change that. This is the output for the input program _return_0.c_:
`	.globl main
main:
	movl	%0, %eax
	ret
	.section .note.GNU-stack,"",@progbits`

Besides that, only a couple of tests for the pretty printer have been added. Let me know if you can think of other cases to test. If you think this is not the right PR to put them in I will remove them.

One important note: running the author's test suite for the whole compiler keeps launching FileNotFoundError for the source c files to use for the test (the ones inside _writing-a-c-compiler-tests/tests/chapter_1/valid/_). In the next days I will look into this problem.

2024-12-03 19:44 UTC, d-u-d-e requested changes

2024-12-03 19:44 UTC, d-u-d-e commented on compiler/compiler_driver.py
> +    else:
Check the following code.
The full compiler is run without stopping at any stage.
So it suffice to go ahead, provided that`use_gcc=False`.
You don't have to create the assembly file at all. It's there as a temporary: `assembly_file`.
There is no need to set the stage to `None`, because the author's compiler tester will not pass any stage argument to the driver.

2024-12-03 19:44 UTC, d-u-d-e commented on compiler/compiler_driver.py
> +    else:
If you perform these changes, you'll be able to run the test suite, and the `FileNotFoundError` you mentioned above disappears. I still get a few assembler warnings such as `Warning: end of file not at end of a line; newline inserted`.

2024-12-03 23:12 UTC, albertoursino requested changes

2024-12-03 23:12 UTC, albertoursino commented on compiler/compiler_driver.py
> +    If the stage is not specified, the whole compiler is executed.
You should leave this function as it is, and run the whole compiler inside the dedicated function above, called `run_compiler`. 

This function, aka `run_compiler_stages`, is used only when using the arguments `--lex`, `--parser` and `--codegen`.

2024-12-03 23:13 UTC, albertoursino commented on compiler/compiler_driver.py
> +    else:
It's important to see [this](https://github.com/d-u-d-e/c-compiler/pull/28#discussion_r1868486541) first.

2024-12-04 00:16 UTC, Fabio-Marangoni commented on compiler/compiler_driver.py
> +    else:
You are right, I forgot you prepared the whole structure for the compiler execution. As you said, now the tests run successfully. The warning disappeared my adding an empty line at the end of the output assembly code. Thank you both @d-u-d-e and @albertoursino .
Next commit I will shift to the "much more appreciated" Intel syntax.

2024-12-04 00:20 UTC, Fabio-Marangoni commented on compiler/compiler_driver.py
> +    If the stage is not specified, the whole compiler is executed.
I adjusted the code according to your suggestions. Thanks for pointing that out.

2024-12-04 01:01 UTC, albertoursino requested changes

2024-12-04 07:41 UTC, d-u-d-e commented on compiler/compiler_driver.py
> +        logger.debug(f"Assembly code:\n{out_code}")
I like `tokenize`.
I would write `emit_assembly_code` instead. It reminds me of `code emission`.
I agree that `generator` is a bad name because it's generic.
I agree that `parsers` is a bad name because it's plural.
Let's change `write_assembly_code` into `emit_assembly_code` or `generate_assembly_code`.

2024-12-04 07:42 UTC, d-u-d-e commented on compiler/compiler_driver.py
>  from compiler.parser import parsers
It's ok to import the needed functions only.

2024-12-04 07:55 UTC, d-u-d-e commented on compiler/code_emission/writer.py
> +    for child in mov_instruction.children:
suggestion: modify `Mov` by adding the source and destination operands properties, much like I did with the `Function` node.
This code does not take into account the order of the `Mov` operands. Are you moving an immediate to a register or from a register? Of course, the latter does not make sense.

2024-12-04 07:55 UTC, d-u-d-e commented on compiler/code_emission/writer.py
> +    :param comment: An optional comment to append after the .globl directive
Use `.global`. I wonder why they decided to save a single character in `globl`. 
The effect is the same: they make the label visible to the linker so that other `.o` files can reference it.

2024-12-04 07:55 UTC, d-u-d-e commented on compiler/code_emission/writer.py
> +    if comment == "":
Can you explain the reason this function exists?
I don't see any comment being added to the code.
Provide some documentation. I suppose this is used to generate comments in the assembly file. Can you suggest an example?

2024-12-04 11:56 UTC, albertoursino commented on compiler/compiler_driver.py
> +        logger.debug(f"Assembly code:\n{out_code}")
I have created a [PR](https://github.com/d-u-d-e/c-compiler/pull/29).

2024-12-04 14:41 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +    for child in mov_instruction.children:
Relying only on the order given by Mov.children was indeed a bad implementation; hence I employed source and destination as properties of Mov in the new [commit](https://github.com/d-u-d-e/c-compiler/pull/28/commits/05158b0441b46c3c77d2e5b2ac0590544c2125a6), as you suggested

2024-12-04 14:42 UTC, Fabio-Marangoni commented on compiler/compiler_driver.py
>  from compiler.parser import parsers
I rearranged it in [this commit](https://github.com/d-u-d-e/c-compiler/pull/28/commits/05158b0441b46c3c77d2e5b2ac0590544c2125a6) by importing the single functions.

2024-12-04 14:48 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +    :param comment: An optional comment to append after the .globl directive
Before changing this I would like to know @albertoursino opinion on this style choice. We can decide to try to keep it as faithful as possible to the compilation of gcc (using `.globl`) or change it at your pleasure (with `.global`) since the result is the same.

2024-12-04 15:25 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +    if comment == "":
With this I addressed the suggestion from the book: "_Consider including comments in your assembly programs
too_". For now I have less of an idea about where we will mostly need these comments; currently I did not add any comment on the assembly code as it is extremely simple. 
With this function it is possible to add a comment in some of the translation steps of writer.py (not for every step, as I can't figure any reason to place comments on certain parts of the assembly code - for instance, in the "ret" instruction -): at the moment we can append a comment at the beginning of a function block or to the row of a move instruction.

Here is an example:
```Python
        .intel_syntax noprefix
        .globl main     #here I am commenting the function
main:
        mov     eax, 0  #and here I am commenting this move instruction
        ret
        .section .note.GNU-stack,"",@progbits
```

I know this will not work anymore for more complex programs where the "translate" functions will be called more than one time, so I will think of something better. Tell me if you prefer to remove it at the moment.

2024-12-04 16:06 UTC, d-u-d-e commented on compiler/code_emission/writer.py
> +    :param comment: An optional comment to append after the .globl directive
Sure. I like `.global` better because it's more portable.

2024-12-04 16:10 UTC, d-u-d-e commented on compiler/code_emission/writer.py
> +    if comment == "":
If it exists in the code base it contributes to the maintenance, even though it is not used.
I like the future, but we can add it when we actually need it.
@albertoursino what do you say?

2024-12-04 22:02 UTC, albertoursino commented on compiler/code_emission/writer.py
> +    :param comment: An optional comment to append after the .globl directive
I haven't found any drawback in using `.global` instead of `.globl`, and since I don't care about this really, I would make @d-u-d-e happy and change it.

2024-12-04 22:06 UTC, albertoursino commented on compiler/code_emission/writer.py
> +    if comment == "":
This function is a nice idea, but I completely agree with @d-u-d-e:

> [...] we can add it when we actually need it.

2024-12-05 00:42 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +    :param comment: An optional comment to append after the .globl directive
If it makes @d-u-d-e happy, it is important. The change has been applied.

2024-12-05 00:50 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +    if comment == "":
I also agree with you. It was more of a reminder for a future implementation rather than a useful function. The add_comment function has been removed in [this commit](https://github.com/d-u-d-e/c-compiler/pull/28/commits/ec40504a9c3d545c5d226fc0353ba100339313e6)

2024-12-05 00:57 UTC, albertoursino requested changes

2024-12-05 00:57 UTC, albertoursino commented on compiler/code_emission/writer.py
> +def write_assembly_code(input_tree: Tree, output_path: str) -> str:
We have decided to rename this function `emit_assembly_code`, right?

2024-12-05 00:57 UTC, albertoursino commented on tests/test_ast.py
The filename is misleading.

2024-12-05 07:43 UTC, d-u-d-e commented
Please resolve the conflicts now that PR #29  has been merged.

2024-12-05 12:06 UTC, Fabio-Marangoni commented on tests/test_ast.py
The file was named test_ast.py for consistency with the naming pattern of the other test files: ### test_filename.py testing functions defined inside ### file_name.py. Would you suggest something like "test_pretty_printer"?

2024-12-05 12:26 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +def write_assembly_code(input_tree: Tree, output_path: str) -> str:
Sorry, apparently I missed this change request. Since we are at it: is the name of file [writer.py](https://github.com/d-u-d-e/c-compiler/blob/feature/code_emission/compiler/code_emission/writer.py) ok for you?

2024-12-05 12:50 UTC, albertoursino commented
> Please resolve the conflicts now that PR #29 has been merged.

I did it.

2024-12-05 13:43 UTC, albertoursino commented on tests/test_ast.py
The problem is that both the parser and the assembly generation modules have an `ast.py` file. I would call them differently, like `parser_ast.py` and `assembly_ast.py`. This way, in this case, the test file would be called `test_assembly_ast.py`. 

Another way could be to leave `ast.py` and call the tests `test_assembly_ast` (ignoring the test file naming convention) but I don't like it because it's misleading again.

I would suggest renaming the `ast.py` files in this PR because it's really little stuff to change. What do you think @d-u-d-e @Fabio-Marangoni ?

2024-12-05 13:47 UTC, albertoursino commented on compiler/code_emission/writer.py
> +def write_assembly_code(input_tree: Tree, output_path: str) -> str:
No, on the base of what we agreed in https://github.com/d-u-d-e/c-compiler/pull/29 you should call it `code_emission.py` (like the name of the directory).

2024-12-05 14:26 UTC, Fabio-Marangoni commented on tests/test_ast.py
> I would call them differently, like `parser_ast.py` and `assembly_ast.py`

Personally I prefer this option.

> This way, in this case, the test file would be called `test_assembly_ast.py`

Note that the current `test_ast.py` file is testing the `generate_pretty_ast_repr()` function, which is imported from `lib/ast/ast.py`: hence this test file should keep its name as it is

2024-12-05 14:34 UTC, albertoursino commented on tests/test_ast.py
Sounds perfect.

2024-12-05 15:20 UTC, Fabio-Marangoni commented on tests/test_ast.py
I applied the suggested changes with [this commit](https://github.com/d-u-d-e/c-compiler/pull/28/commits/bb4b8286ec8afbe42d7cb1bd33b88eb6bb08ec18)

2024-12-05 15:22 UTC, Fabio-Marangoni commented on compiler/code_emission/writer.py
> +def write_assembly_code(input_tree: Tree, output_path: str) -> str:
Names were changed according to your request in [this commit](https://github.com/d-u-d-e/c-compiler/pull/28/commits/bb4b8286ec8afbe42d7cb1bd33b88eb6bb08ec18)

2024-12-06 00:45 UTC, Fabio-Marangoni commented on compiler/compiler_driver.py
> +    if stage not in stages and stage is not None:
Thank you for noticing. It has been removed now.

2024-12-06 01:24 UTC, albertoursino requested changes

2024-12-06 01:24 UTC, albertoursino commented on compiler/code_emission/code_emission.py
> +    return output_code
I would not write the output code to a file inside this function. Instead, let the user handle writing the string to a file (if they want). With this approach you will keep the function flexible and reusable in different contexts.

Functions should focus on a single responsibility, which is a core principle of clean code.

2024-12-06 01:24 UTC, albertoursino commented on compiler/code_emission/code_emission.py
> +    instructions = translate_body(function.body)
I would move this after `label = f"{func_identifier}:\n"` in order to keep a logical order wrt how the strings are concatenated in the return statement.

2024-12-06 12:02 UTC, Fabio-Marangoni commented on compiler/code_emission/code_emission.py
> +    return output_code
> Functions should focus on a single responsibility, which is a core principle of clean code.
This function was conceived with the output file writing as its main responsibility, while returning the string with the whole code is just a "side task" as we use it only to visualize it through the logger.

Anyway, what you are suggesting is to just return `output_code` with this function and let `compiler_driver.py` write it in the .s output file? In my opinion, it would be better to keep `compiler_driver.py` as simple as possible. I will make this change nonetheless, as I see your point.

2024-12-06 12:12 UTC, Fabio-Marangoni commented on compiler/code_emission/code_emission.py
> +    instructions = translate_body(function.body)
Done

2024-12-06 12:45 UTC, albertoursino commented on compiler/code_emission/code_emission.py
> +    return output_code
> This function was conceived with the output file writing as its main responsibility [...]

This is inaccurate, since the main responsibility of `emit_assembly_code`, as written in its specifications, is to:

> Translates the input assembly AST to the corresponding assembly code [...]

`run_compiler` in `compiler_driver.py` has the responsibility to generate a file with the assembly code:

```Python
def run_compiler(input_file: str, output_file: str, use_gcc: bool) -> None:
    """Compiles a preprocessed C source file into an assembly file.

    Args:
        input_file: Path to the preprocessed C file. The file should have a `.i` extension.
        output_file: Path to the compiled assembly file. The file should have a `.s` extension.
    """
```
---
By transferring the responsibility of writing to a file from `run_compiler` to `emit_assembly_code`, you're creating a dependency between the two functions. In doing so, the code becomes harder to maintain.

In general, transferring a responsibility from one function to another creates a risk: any changes to the original function's expectations might break the dependent function.

2024-12-07 10:17 UTC, albertoursino commented
@Fabio-Marangoni how did you know how to write the Assembly code? Because I tried to run GCC and I got this:

```nasm
	.file	"tmp6l53uot_.i"
	.intel_syntax noprefix
	.text
	.globl	main
	.type	main, @function
main:
	mov	eax, 2
	ret
	.size	main, .-main
	.ident	"GCC: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0"
	.section	.note.GNU-stack,"",@progbits
```

While our compiler generates this:

```nasm
        .intel_syntax noprefix
        .global main
main:
        mov     eax, 2

        ret
        .section .note.GNU-stack,"",@progbits
```

Why are they different?

2024-12-07 10:17 UTC, albertoursino commented on compiler/compiler_driver.py
> +                "-masm=intel",
Can you please explain to me what's this and link the relative documentation?

2024-12-07 10:52 UTC, d-u-d-e commented
There's a bunch of assembly pseudo instructions we don't care about like `.size` but the assembly code is the same. I dont really like the extra new line between `mov` and `ret` to be honest.

2024-12-07 13:30 UTC, Fabio-Marangoni commented on compiler/compiler_driver.py
> +                "-masm=intel",
Here is the [source](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#index-masm_003ddialect).
With this option we tell gcc to output assembly code with Intel syntax (the one we agreed on instead of the default AT&T)

2024-12-08 18:33 UTC, d-u-d-e requested changes
Can we remove the extra new line between `mov` and `ret`?

2024-12-08 18:47 UTC, albertoursino commented
> @albertoursino there's a bunch of assembly pseudo instructions we don't care about like `.size` but the assembly code is the same. I dont really like the extra new line between `mov` and `ret` to be honest.

Are you sure you didn't remove useful instructions?

2024-12-08 18:48 UTC, albertoursino submitted a review, later dismissed
Good job @Fabio-Marangoni ! 🚀

2024-12-08 21:11 UTC, Fabio-Marangoni commented
> Can we remove the extra new line between `mov` and `ret`?

Done

2024-12-09 13:51 UTC, albertoursino approved these changes

2024-12-09 15:05 UTC, merged