Parser: recognize complement and negate unary operators.
d-u-d-e/c-compiler pull request #75
Opened 2024-12-24 13:03 UTC by Fabio-Marangoni

This branch features an extension of the previous **parser**: now it can handle the following **unary operations**:
- negation (`-`);
- bitwise complement (`~`).
New tests were added to check the correctness of the parsing of these unary operations, as well as the proper AST visualization provided by the pretty printer.

Here is an example of the AST structure obtained by parsing [nested_ops_2.c](https://github.com/d-u-d-e/c-compiler/blob/main/tests/test_samples/chapter_2/valid/nested_ops_2.c):
```Python
c-compiler$ python3 -m compiler.compiler_driver tests/test_samples/chapter_2/valid/nested_ops_2.c --parse
..............
Program(
   Function(
      name=Identifier(main),
      body=Return(
         Unary operation(
            operator=Negate,
            expression=Unary operation(
               operator=Complement,
               expression=Constant(0)
            )
         )
      )
   )
)
```

2024-12-24 13:37 UTC, d-u-d-e requested changes

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser.py
> +    Unary_operator,
Let's keep the usual camel case: `UnaryOperator`

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser.py
> +    next_token = tokens[0]
Introduce the `peek` function to look at the next token.

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser.py
> +        tok = expect_token_type(Token.TokenType.Constant, tokens)
Introduce `take_token` to avoid double checking the token type.
`expect_token_type` is going to make the comparision another time.

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser.py
> +        expect_token_type(Token.TokenType.OpenParenthesis, tokens)
Here use `take_token` as suggested previously.

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser_ast.py
> +        return "Unary operation"
There's no ambiguity if we call it just `Unary`. It's shorter and results in a cleaner AST repr.

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser.py
> +        expect_token_type(Token.TokenType.Minus, tokens)
Use `take_token` + `peek` as mentioned in another comment.

2024-12-24 13:37 UTC, d-u-d-e commented on compiler/parser/parser_ast.py
> +class Unary_operator(ASTNode):
Write `UnaryOperator` for class names.

2024-12-24 13:37 UTC, d-u-d-e commented on tests/test_parser.py
> +        tokens = [
You can completely avoid the `return` token and parse just the return expression.

2024-12-27 12:18 UTC, Fabio-Marangoni commented on tests/test_parser.py
> +        tokens = [
The superfluous token has been excluded from these tests. Thanks for the suggestion!

2024-12-27 12:19 UTC, Fabio-Marangoni commented on compiler/parser/parser_ast.py
> +class Unary_operator(ASTNode):
The naming mistake has been fixed.

2024-12-27 12:19 UTC, Fabio-Marangoni commented on compiler/parser/parser_ast.py
> +        return "Unary operation"
Your suggestion has been applied. Thanks.

2024-12-27 15:35 UTC, d-u-d-e approved these changes
Well done!

2024-12-27 15:36 UTC, d-u-d-e commented
Do the author's tests pass with the stage `--parse`?

2024-12-27 15:43 UTC, Fabio-Marangoni commented
> Do the author's tests pass with the stage `--parse`?

Yes, all tests are successful.
```Python
~/c-compiler$ ../writing-a-c-compiler-tests/test_compiler ../c-compiler/compiler/compiler_driver.py --chapter 2 --stage parse
----------------------------------------------------------------------
Ran 43 tests in 4.552s

OK
```

2024-12-28 10:47 UTC, albertoursino requested changes
I would do just a few changes, but well done @Fabio-Marangoni ✨

2024-12-28 10:47 UTC, albertoursino commented on compiler/parser/parser.py
> +        raise SyntaxError(f"Expected Unary operator but found {next_token!r}")
I didn't know that you could use `{next_token!r}` instead of explicitly adding quotes like `'{next_token}'`. This way you can write code faster, nice!

2024-12-28 10:47 UTC, albertoursino commented on compiler/parser/parser.py
> +        return Complement(parent=None)
Why don't you use `take_token` for the `Complement` token also?

2024-12-28 10:47 UTC, albertoursino commented on compiler/parser/parser.py
It would be nice to specify the grammar these functions are able to read and parse. We can make the code way clearer this way. For example in this case we can write:

```Python
def parse_expression(tokens: list[Token]) -> Exp:
    """Parses a list of tokens representing an expression and validates the syntax.
        
       Production rules accepted:
       <exp> ::= <int> | <unop> <exp> | "(" <exp> ")"
    """
```

It should be easy to copy them from the book and add them to each parse function. What do you think tho?

2024-12-28 10:47 UTC, albertoursino commented on tests/test_ast.py
> +    def test_generate_pretty_ast_repr_for_parsing(self):
In this test function there are two independent tests. I think you should split them.

2024-12-28 10:47 UTC, albertoursino commented on tests/test_parser.py
> +            self.assertIsInstance(inner_exp, Constant)
It could be improved in readability:

```python
            # both token lists should be parsed likewise
            self.assertIsInstance(unary_node, Unary)
            self.assertIsInstance(unary_node.operator, Negate)
            inner_unary_node = unary_node.exp
            self.assertIsInstance(inner_unary_node, Unary)
            self.assertIsInstance(inner_unary_node.operator, Complement)
            self.assertIsInstance(inner_unary_node.exp, Constant)
```

2024-12-28 11:29 UTC, d-u-d-e commented on compiler/parser/parser.py
> +        return Complement(parent=None)
good catch

2024-12-28 11:29 UTC, d-u-d-e commented on compiler/parser/parser.py
I agree, nice suggestion

2024-12-28 13:14 UTC, Fabio-Marangoni commented on compiler/parser/parser.py
> +        return Complement(parent=None)
Sorry, I missed it. Thanks for pointing it out.

2024-12-28 13:16 UTC, Fabio-Marangoni commented on compiler/parser/parser.py
It is very useful, indeed. I will add it in the next commit.

2024-12-28 13:18 UTC, Fabio-Marangoni commented on tests/test_ast.py
> +    def test_generate_pretty_ast_repr_for_parsing(self):
You are right. I will split it in two separate tests.

2024-12-28 14:47 UTC, Fabio-Marangoni commented on compiler/parser/parser.py
> +        raise SyntaxError(f"Expected Unary operator but found {next_token!r}")
Credits to @d-u-d-e

2024-12-28 14:47 UTC, Fabio-Marangoni commented on tests/test_parser.py
> +            self.assertIsInstance(inner_exp, Constant)
I improved the writing as you suggested.

2024-12-29 02:10 UTC, albertoursino approved these changes

2024-12-29 10:15 UTC, d-u-d-e approved these changes

2024-12-29 10:19 UTC, merged